VitMetaEncoder:
  dim_ffn: 2048
  dropout: 0.1
  input_channels: 3
  input_size: 32
  num_classes: 100
  num_heads: 8
  num_layers: 6
  patch_size: 2
  token_dim: 512
lr_scheduler:
  eta_min: 1.0e-09
  scheduler_type: cosine
optimizer:
  lr: 0.0002
  optim_type: AdamW
